# The receipt for a curation nobody watched happen.
#
# 2,000 works is past the point where "look at it" is a check, so the pool ships
# with its own numbers: what got in, from where, from when, and every bar's
# pass/fail. A quota that cannot be shown to hold has not been met.
module Pool
  class Report
    REGION_NAMES = {
      "europe" => "Europe", "north_america" => "United States & Canada",
      "east_asia" => "East Asia", "south_asia" => "South Asia",
      "southeast_asia" => "Southeast Asia", "west_asia_islamic" => "West Asia & the Islamic world",
      "africa" => "Africa", "latin_america" => "Latin America",
      "oceania" => "Oceania", "unknown" => "Unplaced"
    }.freeze

    def initialize(curator)
      @curator = curator
      @works = curator.selected
    end

    # Story 0018. The one section here that is NOT built from a `curator` —
    # it reads the live seeded `Painting` table, because `artist_slug` is
    # computed at seed time, after the manifest already exists. A class
    # method rather than an instance one for that reason: there is no
    # curator to hold, only the question "what does the shipped app show."
    #
    # A REPORTED number, not an assertion (eng review X2): the slug-based
    # max is measured at 9, over `MAX_PER_ARTIST = 5`, because that constant
    # is enforced on `artist_key` (`lib/pool.rb`), a normalization
    # `Painting#artist_slug` deliberately does not unify with in Release 1
    # (see specs/0018-the-names-you-know/plan.md, E1). Asserting the slug
    # number would fail today with no re-curation available to fix it.
    def self.artist_slug_section
      rows = Painting.where.not(artist_slug: nil).pluck(:artist, :artist_slug)
      by_slug = rows.group_by(&:last)
      max = by_slug.values.map(&:size).max.to_i
      merge_groups = by_slug.select { |_, group| group.map(&:first).uniq.size > 1 }

      lines = []
      lines << "## Artist slugs (live, story 0018)"
      lines << ""
      lines << "#{by_slug.size} slugs over #{rows.size} works. Largest slug page: #{max} works " \
        "(Pool::Curator::MAX_PER_ARTIST is #{Curator::MAX_PER_ARTIST}, enforced on artist_key — not the same count)."
      lines << ""
      if merge_groups.any?
        lines << "#{merge_groups.size} slug(s) merge more than one spelling:"
        merge_groups.each do |slug, group|
          lines << "  #{slug}: #{group.map(&:first).uniq.sort.inspect}"
        end
      else
        lines << "No slug currently merges more than one distinct artist string."
      end
      lines.join("\n")
    end

    def to_markdown
      <<~MARKDOWN
        # Pool report

        Generated by `bin/rails pool:curate` for story 0013. Every number below is
        counted from the committed manifest, `db/seeds/paintings.json`.

        **#{@works.size} paintings, #{@works.map(&:source).uniq.size} museums.**

        ## Bars

        | Bar | Have | Want | |
        |---|---:|---:|:--|
        #{bar_rows}

        ## By museum

        | Museum | Works | Share | Carrying text |
        |---|---:|---:|---:|
        #{source_rows}

        ## By region

        | Region | Works | Share |
        |---|---:|---:|
        #{region_rows}

        ## By era

        | Era | Works | Share |
        |---|---:|---:|
        #{era_rows}

        ## Range, stated plainly

        #{range_note}

        ## Rejected before selection

        #{rejection_rows}
      MARKDOWN
    end

    private

    def share(count) = "#{(100.0 * count / @works.size).round(1)}%"

    def bar_rows
      @curator.bars.map { |name, (have, want, ok)|
        "| #{name} | #{have} | #{want} | #{ok ? '✓' : '✗ FAIL'} |"
      }.join("\n")
    end

    def source_rows
      @works.group_by(&:source).sort_by { |_, w| -w.size }.map { |key, works|
        name = Painting::SOURCES.dig(key, :name) || key
        "| #{name} | #{works.size} | #{share(works.size)} | #{works.count(&:text?)} |"
      }.join("\n")
    end

    def region_rows
      @works.group_by(&:region).sort_by { |_, w| -w.size }.map { |key, works|
        "| #{REGION_NAMES[key] || key} | #{works.size} | #{share(works.size)} |"
      }.join("\n")
    end

    ERAS = [
      [ "before 1500", ->(y) { y.positive? && y < 1500 } ],
      [ "1500–1699", ->(y) { y.between?(1500, 1699) } ],
      [ "1700–1799", ->(y) { y.between?(1700, 1799) } ],
      [ "1800–1899", ->(y) { y.between?(1800, 1899) } ],
      [ "1900 and later", ->(y) { y >= 1900 } ],
      [ "undated", ->(y) { y.zero? } ]
    ].freeze

    def era_rows
      ERAS.map { |name, test|
        count = @works.count { |c| test.call(c.year.to_i) }
        "| #{name} | #{count} | #{share(count)} |"
      }.join("\n")
    end

    # Two things the numbers above would otherwise let a reader misread.
    def range_note
      african = @works.select { |c| c.region == "africa" }
      egyptian = african.count { |c| "#{c.country} #{c.culture}".match?(/egypt/i) }
      mute = @works.reject(&:text?).group_by(&:source).transform_values(&:size)

      [
        "**African representation is #{african.size} works (#{share(african.size)})**, of which " \
        "#{egyptian} are Egyptian. Persona 3 asked for Benin bronzes; bronzes are not paintings, and " \
        "the African holdings of all four museums are overwhelmingly sculpture, textile and object. " \
        "This is finding F2 in the plan — a named gap, not a solved one.",
        "**#{@works.count { |c| !c.text? }} works carry no museum text** " \
        "(#{mute.map { |k, v| "#{k} #{v}" }.join(', ')}). Under story 0005 those days cannot be " \
        "published without a hand-written note, which is what the #{(Curator::MIN_TEXT_SHARE * 100).to_i}% " \
        "text bar exists to bound."
      ].join("\n\n")
    end

    def rejection_rows
      return "_None._" if @curator.rejected.empty?

      @curator.rejected.sort_by { |_, v| -v }.map { |reason, count|
        "- **#{reason.to_s.tr('_', ' ')}** — #{count}"
      }.join("\n")
    end
  end
end
