# The receipt for a curation nobody watched happen.
#
# 2,000 works is past the point where "look at it" is a check, so the pool ships
# with its own numbers: what got in, from where, from when, and every bar's
# pass/fail. A quota that cannot be shown to hold has not been met.
module Pool
  class Report
    REGION_NAMES = {
      "europe" => "Europe", "north_america" => "United States & Canada",
      "east_asia" => "East Asia", "south_asia" => "South Asia",
      "southeast_asia" => "Southeast Asia", "west_asia_islamic" => "West Asia & the Islamic world",
      "africa" => "Africa", "latin_america" => "Latin America",
      "oceania" => "Oceania", "unknown" => "Unplaced"
    }.freeze

    def initialize(curator)
      @curator = curator
      @works = curator.selected
    end

    # Story 0018. The one section here that is NOT built from a `curator` —
    # it reads the live seeded `Painting` table, because `artist_slug` is
    # computed at seed time, after the manifest already exists. A class
    # method rather than an instance one for that reason: there is no
    # curator to hold, only the question "what does the shipped app show."
    #
    # A REPORTED number, not an assertion (eng review X2): the slug-based
    # max is measured at 9, over `MAX_PER_ARTIST = 5`, because that constant
    # is enforced on `artist_key` (`lib/pool.rb`), a normalization
    # `Painting#artist_slug` deliberately does not unify with in Release 1
    # (see specs/0018-the-names-you-know/plan.md, E1). Asserting the slug
    # number would fail today with no re-curation available to fix it.
    def self.artist_slug_section
      rows = Painting.where.not(artist_slug: nil).pluck(:artist, :artist_slug)
      by_slug = rows.group_by(&:last)
      max = by_slug.values.map(&:size).max.to_i
      merge_groups = by_slug.select { |_, group| group.map(&:first).uniq.size > 1 }

      lines = []
      lines << "## Artist slugs (live, story 0018)"
      lines << ""
      lines << "#{by_slug.size} slugs over #{rows.size} works. Largest slug page: #{max} works " \
        "(Pool::Curator::MAX_PER_ARTIST is #{Curator::MAX_PER_ARTIST}, enforced on artist_key — not the same count)."
      lines << ""
      if merge_groups.any?
        lines << "#{merge_groups.size} slug(s) merge more than one spelling:"
        merge_groups.each do |slug, group|
          lines << "  #{slug}: #{group.map(&:first).uniq.sort.inspect}"
        end
      else
        lines << "No slug currently merges more than one distinct artist string."
      end
      lines.join("\n")
    end

    # Story 0022 Release 2. Live, not manifest-derived — same reason
    # `artist_slug_section` above reads the seeded table instead of a
    # curator: `genre` reaches the manifest via `Pool::GenreFill`, a
    # standalone enrichment pass that runs after curation, and the question
    # this answers is "what does the shipped app show."
    def self.genre_section
      by_source = Painting.group(:source).count
      covered = Painting.where.not(genre: nil).group(:source).count
      by_bucket = Painting.where.not(genre: nil).group(:genre).count.sort_by { |_, count| -count }
      # `displayed_facet_values` applies MIN_FACET_WORKS — this is the exact
      # set /feed actually renders as a control, not every bucket that has
      # any coverage at all (bug, caught by reading this report's own first
      # real output: an earlier draft printed all 11 buckets and claimed all
      # of them "clear the floor").
      displayed = Painting.displayed_facet_values(:genre)

      lines = []
      lines << "## Genre (live, story 0022 Release 2)"
      lines << ""
      lines << "Museum-native subject tags only — AIC `subject_titles`, MET `tags`. Wikidata " \
        "P135 artist-movement was scoped out of Release 2 during eng review (IDEAS.md)."
      lines << ""
      by_source.keys.sort.each do |source|
        total = by_source[source]
        n = covered[source].to_i
        lines << "  #{source}: #{n}/#{total} (#{total.zero? ? 0 : (100.0 * n / total).round}%)"
      end
      lines << ""
      lines << "#{by_bucket.size} value(s) have any coverage; #{displayed.size} clear " \
        "MIN_FACET_WORKS (#{Painting::MIN_FACET_WORKS}) and render as a control on /feed:"
      by_bucket.each do |genre, count|
        lines << "  #{genre}: #{count}#{" — below the floor, ALL only" unless displayed.include?(genre)}"
      end
      lines.join("\n")
    end

    def to_markdown
      <<~MARKDOWN
        # Pool report

        Generated by `bin/rails pool:curate` for story 0013. Every number below is
        counted from the committed manifest, `db/seeds/paintings.json`.

        **#{@works.size} paintings, #{@works.map(&:source).uniq.size} museums.**

        ## Bars

        | Bar | Have | Want | |
        |---|---:|---:|:--|
        #{bar_rows}

        ## By museum

        | Museum | Works | Share | Carrying text |
        |---|---:|---:|---:|
        #{source_rows}

        ## By region

        | Region | Works | Share |
        |---|---:|---:|
        #{region_rows}

        ## By era

        | Era | Works | Share |
        |---|---:|---:|
        #{era_rows}

        ## Range, stated plainly

        #{range_note}

        #{themes_section}

        #{recognizable_section}

        #{place_as_artist_section}

        ## Rejected before selection

        #{rejection_rows}
      MARKDOWN
    end

    private

    # Story 0026. The demand stage's want/took/shortfall, per theme — the
    # 0019 report idiom (below) extended, and the artifact decisions/0016
    # prediction 2 (Sep 20) is read against. `want` is an absolute floor on
    # the whole pool, so `took` can exceed the newly-added count when a
    # theme already had pinned stock.
    # Curation-time snapshot: what `fill_themes` itself achieved, before
    # `pool:genre_fill` runs. Accurate for the 4 tradition-route themes
    # (Persian/Thangka/Ukiyo-e/Madhubani — `Tradition.from_strings` never
    # depends on a genre_fill-written field), but can overstate the 6
    # genre-route themes: genre_fill's native museum tags legitimately
    # outrank a title-inferred value per the seed ladder (story 0025), so a
    # candidate `fill_themes` counted as e.g. "Vanitas" can ship tagged
    # "Still Life" instead. `Report.theme_recount_section` (below) is the
    # authoritative post-pipeline number — code review, story 0026.
    def themes_section
      themes = @curator.themes
      return "" if themes.blank?

      lines = [ "## Theme quotas at curation time (story 0026)", "" ]
      lines << "| Theme | Want | Took | Shortfall |"
      lines << "|---|---:|---:|---:|"
      themes.each do |name, r|
        lines << "| #{name} | #{r[:want]} | #{r[:took]} | #{r[:shortfall].zero? ? "—" : r[:shortfall]} |"
      end
      short = themes.select { |_, r| r[:shortfall].positive? }
      if short.any?
        lines << ""
        lines << "**#{short.size} theme(s) short of their floor** — stock failed adjudication " \
                 "(bad plates, wrong attribution) rather than the matcher missing candidates; " \
                 "this is decisions/0016 falsification 2, logged per-theme not papered over."
      end
      lines << ""
      lines << "Genre-route counts above are curation-time only — run `bin/rails pool:genre_fill`, " \
               "then `bin/rails pool:report` for the authoritative post-pipeline recount."
      lines.join("\n")
    end

    # Story 0026, code review finding: `themes_section` above is a
    # curation-time snapshot and can overstate a genre-route theme once
    # `pool:genre_fill` reassigns a candidate's genre by native museum tag
    # (tag > title, the seed ladder). This recomputes every theme from the
    # COMMITTED MANIFEST through that same ladder — the number a reader
    # would actually see — same idiom as `genre_section` reading live data
    # instead of the curator. Class method: called from `pool:genre_fill`
    # (to correct the report right after the pipeline step that can
    # invalidate it) and `pool:report` (to print it standalone).
    def self.theme_recount_section(manifest: Pool::MANIFEST)
      rows = JSON.parse(manifest.read)

      lines = [ "## Theme quotas, final (story 0026 — post pool:genre_fill)", "" ]
      lines << "| Theme | Want | Have | Shortfall |"
      lines << "|---|---:|---:|---:|"
      short = []
      Pool::ThemeTargets::TABLE.each do |name, kind, values, want|
        values = Array(values)
        have = rows.count { |row| values.include?(Pool::ThemeTargets.ladder_value_for(kind, row)) }
        shortfall = [ want - have, 0 ].max
        short << name if shortfall.positive?
        lines << "| #{name} | #{want} | #{have} | #{shortfall.zero? ? "—" : shortfall} |"
      end
      if short.any?
        lines << ""
        lines << "**#{short.size} theme(s) short of their floor after the full pipeline** — " \
                 "decisions/0016 falsification 2, logged here rather than only in the " \
                 "curation-time table above (which can disagree once `genre_fill` reassigns a tag)."
      end
      lines.join("\n")
    end

    # Story 0019. What the recognizable-name stage managed, and where it fell
    # short — a name the mirrors can only supply one work for gets one, and
    # that is supply, not a bug. Printed so the difference stays visible.
    def recognizable_section
      filled = @curator.recognizable
      return "" if filled.blank?

      short = filled.select { |_, r| r[:taken] < Recognizable::DEPTH }
      missed = filled.select { |_, r| r[:taken].zero? }
      lines = [ "## Recognizable names (story 0019)", "" ]
      lines << "#{filled.size} of #{Recognizable.names.size} names on the 0007 list matched a candidate; " \
               "#{filled.sum { |_, r| r[:taken] }} works taken at a depth target of #{Recognizable::DEPTH}."
      lines << ""
      if missed.any?
        lines << "**#{missed.size} matched but took nothing** — every candidate was refused, either by a cap " \
                 "(`room_for?`) or by the plate resolver finding no reachable image (`resolved?`, the MIA " \
                 "403 case). Either way the fill is incomplete rather than a bar broken:"
        lines << ""
        missed.keys.first(20).each { |name| lines << "- #{name}" }
        lines << ""
      end
      capped = short.reject { |name, _| missed.key?(name) }
      if capped.any?
        lines << "#{capped.size} name(s) below the depth target, supply-limited or capped:"
        lines << ""
        capped.first(20).each { |name, r| lines << "- #{name} — #{r[:taken]} of #{r[:available]} available" }
        lines << ""
      end
      if @curator.collisions.present?
        lines << "**Alias collisions:** " +
                 @curator.collisions.map { |x| "`#{x[:slug]}` kept #{x[:kept]}, dropped #{x[:dropped]}" }.join("; ")
        lines << ""
      end
      lines.join("\n")
    end

    # The deny-list's one structural gap, made visible (IDEAS.md deferred
    # finding 3). `Painting::NOT_AN_ARTIST` is a list of exact strings, so a
    # place or culture string a future source introduces becomes a live artist
    # page silently, with no test and no handling.
    #
    # TWO rules, because the first draft had only the "single-word slug holding
    # more than one work" rule and the eng review measured it: **12 of 12 false
    # positives and 0 of 30 true positives** on the shipped manifest. Museums do
    # not write culture-as-artist as a bare single word — they qualify it
    # ("India (Calcutta)", 5 works live) or inflect it ("Spanish", "Ancient
    # Egyptian"). The rule flagged Govardhan, Chokha, Fayzullah, Purkhu and
    # Basavana, who are real Mughal and Pahari painters, and missed all 49 works
    # over 31 strings that are actually places.
    #
    # Both stay REPORTED lines, never assertions: two of the 31 — "Mewar Stipple
    # Master" and "Ugolino da Siena" — are real painters named for a place, so
    # only a human can finish the call. The pass extends `NOT_AN_ARTIST` before
    # `db:seed`, which is the loop story 0018's E2 established.
    def place_as_artist_section
      slugs = @works.filter_map { |c| Painting.artist_slug_for(c.artist) }
      single = slugs.tally.select { |slug, _| slug.exclude?("-") }.sort_by { |_, count| -count }
      # `slugs` is already `artist_slug_for` output, so a denied string is
      # absent from it by construction.
      # Filtered through `artist_slug_for`, exactly like `single` above. The
      # first version selected on `place_shaped?` alone, so the committed
      # report listed 35 strings under the header "this ships as a live
      # /artists/:slug page" when 34 of them were already denied and shipped
      # nothing. A reviewer had to re-check 34 handled strings to find the one
      # that mattered — which is plausibly why "Anonymous" survived the pass
      # and reached production (code review finding 1).
      placey = @works.map(&:artist).compact
                     .select { |name| Pool.place_shaped?(name) && Painting.artist_slug_for(name).present? }
                     .tally.sort_by { |_, count| -count }
      return "" if single.empty? && placey.empty?

      [
        "## Artist strings that may not be artists",
        "",
        "Read both lists before seeding. A place or culture string here is `Painting::NOT_AN_ARTIST` " \
        "missing an entry, and it ships as a live `/artists/:slug` page.",
        "",
        "**Single-word slugs** (#{single.size}) — mostly real one-word painters; scan for a country:",
        "",
        single.map { |slug, count| "- `#{slug}` — #{count}" }.join("\n"),
        "",
        "**Still-linkable strings containing a place or culture word** (#{placey.size} strings, " \
        "#{placey.sum(&:last)} works) — already-denied strings are omitted, so everything below is live:",
        "",
        placey.map { |name, count| "- #{name.inspect} — #{count}" }.join("\n"),
        ""
      ].join("\n")
    end

    def share(count) = "#{(100.0 * count / @works.size).round(1)}%"

    def bar_rows
      @curator.bars.map { |name, (have, want, ok)|
        "| #{name} | #{have} | #{want} | #{ok ? '✓' : '✗ FAIL'} |"
      }.join("\n")
    end

    def source_rows
      @works.group_by(&:source).sort_by { |_, w| -w.size }.map { |key, works|
        name = Painting::SOURCES.dig(key, :name) || key
        "| #{name} | #{works.size} | #{share(works.size)} | #{works.count(&:text?)} |"
      }.join("\n")
    end

    def region_rows
      @works.group_by(&:region).sort_by { |_, w| -w.size }.map { |key, works|
        "| #{REGION_NAMES[key] || key} | #{works.size} | #{share(works.size)} |"
      }.join("\n")
    end

    ERAS = [
      [ "before 1500", ->(y) { y.positive? && y < 1500 } ],
      [ "1500–1699", ->(y) { y.between?(1500, 1699) } ],
      [ "1700–1799", ->(y) { y.between?(1700, 1799) } ],
      [ "1800–1899", ->(y) { y.between?(1800, 1899) } ],
      [ "1900 and later", ->(y) { y >= 1900 } ],
      [ "undated", ->(y) { y.zero? } ]
    ].freeze

    def era_rows
      ERAS.map { |name, test|
        count = @works.count { |c| test.call(c.year.to_i) }
        "| #{name} | #{count} | #{share(count)} |"
      }.join("\n")
    end

    # Two things the numbers above would otherwise let a reader misread.
    def range_note
      african = @works.select { |c| c.region == "africa" }
      egyptian = african.count { |c| "#{c.country} #{c.culture}".match?(/egypt/i) }
      mute = @works.reject(&:text?).group_by(&:source).transform_values(&:size)

      [
        "**African representation is #{african.size} works (#{share(african.size)})**, of which " \
        "#{egyptian} are Egyptian. Persona 3 asked for Benin bronzes; bronzes are not paintings, and " \
        "the African holdings of all four museums are overwhelmingly sculpture, textile and object. " \
        "This is finding F2 in the plan — a named gap, not a solved one.",
        "**#{@works.count { |c| !c.text? }} works carry no museum text** " \
        "(#{mute.map { |k, v| "#{k} #{v}" }.join(', ')}). Under story 0005 those days cannot be " \
        "published without a hand-written note, which is what the #{(Curator::MIN_TEXT_SHARE * 100).to_i}% " \
        "text bar exists to bound."
      ].join("\n\n")
    end

    def rejection_rows
      return "_None._" if @curator.rejected.empty?

      @curator.rejected.sort_by { |_, v| -v }.map { |reason, count|
        "- **#{reason.to_s.tr('_', ' ')}** — #{count}"
      }.join("\n")
    end
  end
end
